### ISSUE TITLE
Add Bo to this organization

### ISSUE THREAD

**Issue by boturnbow** [CollegeTipp/collegetipp.github.io#1]
Please!

**Comment by joaquinvaldez** [comment]
Hi @boturnbow I believe you are added!  True?

**Comment by boturnbow** [comment]
I don't see any differences. I can't edit a file.

**Comment by joaquinvaldez** [comment]
@boturnbow I created a Team called SAF and added you to it.

**Comment by boturnbow** [comment]
I think you want to add me to Owners. Otherwise, I have no privs.

**Comment by boturnbow** [comment]
See https://github.com/orgs/CollegeTipp/teams/saf/repositories

**Comment by joaquinvaldez** [comment]
OK team SAF has Admin access.  So you should be able to do what you like.

**Comment by joaquinvaldez** [comment]
@boturnbow you should have admin access now.

**Comment by boturnbow** [comment]
SAF team has admin access to its repos, but SAF team does not have any repos: https://github.com/orgs/CollegeTipp/teams/saf/repositories I think it's just easier to make us part of the owner team and then we have access to all repos for the organization. That's what I did for masafaa: https://github.com/orgs/masfaa/teams/owners

**Comment by joaquinvaldez** [comment]
Ok You are now part of the Owner  Team.  For some reason I couldn't add you at first, but now you are there.

**Comment by boturnbow** [comment]
That works for me!
